In [59]:
import numpy as np

In [61]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [63]:
a1 - a2


array([-5, -5, -5, -5, -5])

In [65]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [67]:
a1 // a2

array([0, 0, 0, 0, 0])

In [69]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [71]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

deep and shallow copy

In [74]:
a  = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [76]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [77]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [80]:
a[4:6] * 10

array([50, 60])

In [82]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [84]:
a 
b = a

In [86]:
b[2] =24
b

array([ 1,  2, 24,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [88]:
a

array([ 1,  2, 24,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [90]:
a 
b =a.copy()

In [92]:
b[3]=88
b

array([ 1,  2, 24, 88,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [94]:
a

array([ 1,  2, 24,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

matrix operations

In [97]:
A = np.array([[1,2],[3,4]])

In [99]:
B = np.array([[5,6],[7,8]])

In [101]:
A

array([[1, 2],
       [3, 4]])

In [103]:
B

array([[5, 6],
       [7, 8]])

In [105]:
A @ B

array([[19, 22],
       [43, 50]])

In [109]:
 A.T

array([[1, 3],
       [2, 4]])

stacking array

In [113]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [115]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [117]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [119]:
np.column_stack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

splitting array

In [121]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [135]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [137]:
a = np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [146]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
