In [1]:
import numpy as np


In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

In [7]:
np.array(a)

array([1, 2, 3, 4])

In [9]:
l = [{1,3,2},{4,5,6},{7,8,9}]
l

[{1, 2, 3}, {4, 5, 6}, {7, 8, 9}]

In [11]:
np.array(l)

array([{1, 2, 3}, {4, 5, 6}, {8, 9, 7}], dtype=object)

In [37]:
arr = np.arange(1,11,4)
arr

array([1, 5, 9])

In [35]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [31]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [41]:
arr = np.ones((6,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
arr = np.linspace(1,5,2)

In [45]:
arr

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [6]:
np.random.rand(10)

array([0.09144242, 0.21299332, 0.71463671, 0.68024847, 0.89522601,
       0.48024222, 0.82360164, 0.95344063, 0.8141691 , 0.0360501 ])

In [2]:
import numpy as np

In [15]:
np.random.randn(10)

array([-0.29870487,  0.35758001, -1.01129439,  0.13177386,  1.55629483,
       -0.00916218, -2.52767319,  0.87937861,  0.60604647,  1.18945325])

In [19]:
np.random.randint(10,30,20)

array([10, 25, 15, 17, 29, 17, 13, 23, 20, 14, 11, 17, 26, 25, 29, 21, 18,
       15, 29, 19])

In [23]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr.shape

(3, 3)

In [27]:
arr.size

9

In [29]:
arr.dtype

dtype('int32')

In [31]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr.min()

1

In [37]:
arr.max()

9

In [40]:
arr.sum()

45

In [44]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [46]:
arr.mean()

5.0

In [48]:
arr.std()

2.581988897471611

In [50]:
arr.argmax()

8

In [52]:
arr.argmin()

0

In [54]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [56]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [58]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])