In [1]:
import numpy as np

In [5]:
arr = np.arange(12,30)
arr

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29])

In [7]:
arr[6]

18

In [21]:
arr_slice = arr[2:8]
arr_slice

array([14, 15, 16, 17, 18, 19])

In [19]:
arr[3::2]

array([15, 17, 19, 21, 23, 25, 27, 29])

In [23]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [25]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [31]:
slice2 = arr[3:,3:]
slice2

array([[19, 20],
       [24, 25],
       [29, 30]])

In [39]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [41]:
bool_indexing = arr %2 ==0
bool_indexing

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [43]:
arr = arr[bool_indexing]
arr

array([12, 14, 16, 18, 20])